name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump issues workflow
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
